// Customer pages
export { default as Landing } from './Landing'
export { default as Register } from './Register'
export { default as Login } from './Login'
export { default as OTPVerification } from './OTPVerification'
export { default as Profile } from './Profile'
export { default as RegisterProduct } from './RegisterProduct'
export { default as MyProducts } from './MyProducts'
export { default as ProductDetail } from './ProductDetail'
export { default as Enquiry } from './Enquiry'
export { default as WarrantyRules } from './WarrantyRules'
export { default as CustomerLogout } from './CustomerLogout'
