import { useEffect, useMemo, useState } from 'react'
import toast from 'react-hot-toast'
import { ChevronLeft, ChevronRight, Eye, Loader2, MessageSquare, Search, Store, UserRound, X } from 'lucide-react'
import api from '../../api/axios'

const LABELS = { q1: 'Mattress look', q2: 'Discovery source', q3: 'Product impression', q4: 'Dealer information', q5: 'Service experience', q6: 'Prices', q7: 'Product quality', q8: 'Delivery timeliness', q9: 'Customer support', q10: 'Would recommend', q11: 'Previously reported problem', q12: 'Expectation improvements', q13: 'Service-related problem', q14: 'Additional comments' }
const LIMIT = 25
function formatDate(value) { return value ? new Date(value).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' }) : 'N/A' }
function responseTone(value) { if (['Very Good', 'Yes'].includes(value)) return 'bg-success-50 text-success-700'; if (['Poor', 'No'].includes(value)) return 'bg-danger-50 text-danger-700'; if (value === 'Good') return 'bg-brand-50 text-brand-700'; return 'bg-surface-100 text-surface-700' }

export default function FeedbackAdmin() {
  const [feedbacks, setFeedbacks] = useState([]), [search, setSearch] = useState(''), [loading, setLoading] = useState(true), [total, setTotal] = useState(0), [page, setPage] = useState(0), [selected, setSelected] = useState(null)
  async function load(q = search, nextPage = page) { setLoading(true); try { const params = { skip: nextPage * LIMIT, limit: LIMIT, ...(q.trim() ? { q: q.trim() } : {}) }; const response = await api.get('/feedback', { params }); setFeedbacks(response.data.feedbacks || []); setTotal(response.data.total || 0) } catch (error) { toast.error(error.response?.data?.detail || 'Failed to load feedback') } finally { setLoading(false) } }
  useEffect(() => { load('', 0) }, [])
  const dealers = useMemo(() => new Set(feedbacks.map((item) => item.dealer_name).filter(Boolean)).size, [feedbacks])
  const pages = Math.max(1, Math.ceil(total / LIMIT))
  function searchNow(event) { event.preventDefault(); setPage(0); load(search, 0) }
  function go(next) { setPage(next); load(search, next) }

  return <section className="space-y-5">
    <div className="flex flex-col gap-4 border-b border-surface-200 pb-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-brand-700">Voice of customer</p><h1 className="mt-2 text-3xl font-bold text-surface-950">Customer Feedback</h1><p className="mt-1 text-sm text-surface-500">Scan responses quickly; open only the ones you want to inspect.</p></div><div className="flex gap-2"><Stat value={total} label="Responses" /><Stat value={dealers} label="Dealers on page" /></div></div>
    <form onSubmit={searchNow} className="flex gap-2 rounded-xl border border-surface-200 bg-white p-3 shadow-sm"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-surface-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} className="input pl-9" placeholder="Search piece, customer, item or dealer" /></div><button className="btn-primary">Search</button></form>
    <div className="overflow-hidden rounded-xl border border-surface-200 bg-white shadow-sm">
      <div className="hidden grid-cols-[1.1fr_1.4fr_1fr_170px_80px] gap-4 border-b border-surface-200 bg-surface-50 px-5 py-3 text-xs font-semibold uppercase tracking-wide text-surface-500 lg:grid"><span>Piece</span><span>Customer / Product</span><span>Dealer</span><span>Submitted</span><span>Action</span></div>
      {loading ? <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-brand-700" /></div> : feedbacks.length ? <div className="divide-y divide-surface-100">{feedbacks.map((feedback) => <div key={feedback.id} className="grid gap-3 px-5 py-3.5 transition hover:bg-brand-50/30 lg:grid-cols-[1.1fr_1.4fr_1fr_170px_80px] lg:items-center lg:gap-4"><div><p className="text-sm font-bold text-surface-950">{feedback.piece}</p><p className="text-xs text-surface-500">{feedback.answers?.q1 || 'No rating'}</p></div><div className="min-w-0"><p className="truncate text-sm font-semibold text-surface-900">{feedback.customer_name || feedback.customer_email}</p><p className="truncate text-xs text-surface-500">{feedback.item_name || 'Product'}</p></div><p className="truncate text-sm text-surface-700">{feedback.dealer_name || 'N/A'}</p><p className="text-xs text-surface-500">{formatDate(feedback.submitted_at)}</p><button onClick={() => setSelected(feedback)} className="inline-flex items-center gap-1.5 text-sm font-semibold text-brand-700 hover:text-brand-900"><Eye className="h-4 w-4" />View</button></div>)}</div> : <div className="p-12 text-center"><MessageSquare className="mx-auto h-10 w-10 text-surface-400" /><p className="mt-3 text-sm text-surface-600">No feedback found.</p></div>}
      {total > LIMIT && <div className="flex items-center justify-between border-t border-surface-200 px-5 py-3"><p className="text-xs text-surface-500">Page {page + 1} of {pages}</p><div className="flex gap-1"><button onClick={() => go(page - 1)} disabled={page === 0} className="rounded-lg border border-surface-200 p-2 disabled:opacity-30"><ChevronLeft className="h-4 w-4" /></button><button onClick={() => go(page + 1)} disabled={page + 1 >= pages} className="rounded-lg border border-surface-200 p-2 disabled:opacity-30"><ChevronRight className="h-4 w-4" /></button></div></div>}
    </div>
    {selected && <FeedbackDrawer feedback={selected} onClose={() => setSelected(null)} />}
  </section>
}

function Stat({ value, label }) { return <div className="min-w-28 rounded-xl border border-surface-200 bg-white px-4 py-2.5 text-center shadow-sm"><p className="text-xl font-bold text-surface-950">{value}</p><p className="text-[11px] uppercase tracking-wide text-surface-500">{label}</p></div> }
function FeedbackDrawer({ feedback, onClose }) {
  return <div className="fixed inset-0 z-[70] flex justify-end bg-slate-950/45 backdrop-blur-sm" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><aside className="h-full w-full max-w-2xl overflow-y-auto bg-surface-50 shadow-2xl"><div className="sticky top-0 z-10 border-b border-surface-200 bg-white/95 px-6 py-5 backdrop-blur"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-brand-700">Feedback response</p><h2 className="mt-1 text-2xl font-bold text-surface-950">Piece {feedback.piece}</h2><p className="mt-1 text-xs text-surface-500">{formatDate(feedback.submitted_at)}</p></div><button onClick={onClose} className="rounded-lg p-2 text-surface-500 hover:bg-surface-100"><X className="h-5 w-5" /></button></div></div><div className="space-y-5 p-6"><div className="grid gap-3 sm:grid-cols-2"><Info icon={UserRound} label="Customer" value={feedback.customer_name || feedback.customer_email} sub={feedback.customer_email} /><Info icon={Store} label="Dealer" value={feedback.dealer_name || 'N/A'} sub={feedback.item_name} /></div><section><h3 className="mb-3 text-sm font-bold text-surface-900">Quick responses</h3><div className="grid gap-2 sm:grid-cols-2">{Object.entries(LABELS).slice(0, 11).map(([key, label]) => <div key={key} className="flex items-center justify-between gap-3 rounded-xl border border-surface-200 bg-white px-4 py-3"><span className="text-xs font-medium text-surface-600">{label}</span><span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-bold ${responseTone(feedback.answers?.[key])}`}>{feedback.answers?.[key] || 'N/A'}</span></div>)}</div></section><section><h3 className="mb-3 text-sm font-bold text-surface-900">Written feedback</h3><div className="space-y-3">{Object.entries(LABELS).slice(11).map(([key, label]) => <div key={key} className="rounded-xl border border-surface-200 bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wide text-surface-500">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-surface-800">{feedback.answers?.[key] || 'No comment provided.'}</p></div>)}</div></section></div></aside></div>
}
function Info({ icon: Icon, label, value, sub }) { return <div className="flex gap-3 rounded-xl border border-surface-200 bg-white p-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-brand-50 text-brand-700"><Icon className="h-4 w-4" /></span><div className="min-w-0"><p className="text-xs text-surface-500">{label}</p><p className="truncate text-sm font-semibold text-surface-900">{value}</p>{sub && <p className="truncate text-xs text-surface-500">{sub}</p>}</div></div> }
